### PR TITLE
cursFeatureWriter: Support multiple entry/exit anchor pairs

### PR DESCRIPTION
**Pull request by khaledhosny**
Support dot suffixed entry and exit anchor names, in addition to unsuffixed names. Each anchor pair creates a new lookups. Lookups are sorted by anchor names.

### CODE REVIEW

**Comment by khaledhosny** [comment]
Glyphs supports such suffixed cursive anchor names, but I don’t know about other font editors, so in a sense this is Glyphs-specific, but UFO spec is silent on cursive anchors so I think the whole concept is Glyphs-specific.

@schriftgestalt, this supports `entry.1`, `entry.foo` etc, does glyph support suffix seperators other than `.`?

**Comment by anthrotype** [comment]
Thanks Khaled, even if only Glyphs.app supports this, I think it's OK to add this here.

**Review by anthrotype — APPROVED** [review]

**Comment by khaledhosny** [comment]
> I just check my code. All anchors that start with "exit/entry" a used for the curs feature. Everything following is used as suffix. So "exitABC" or "entry1234" is valid.

Interesting. Since lookup for `entry.1` is named `curs_1`, what happens if there is also `entry_1` anchor?

> Glyphs uses "exit/entry" that have one char (e.g. `#` or `😀`) prefix for component alignment but ignores them for the curs feature.

I think we already skip such anchors in glyphsLib markFeatureWriter, and since they don’t start with `entry` or `exit`, they would be skipped here as well.

**Comment by schriftgestalt** [comment]
> Interesting. Since lookup for entry.1 is named curs_1, what happens if there is also entry_1 anchor?

Those would end up in the same lookup.

**Review by moyogo — APPROVED** [review]
Looks good to me!

**Comment by moyogo** [comment]
Maybe Glyphs.app can use the "." like in the test with this semantics?

**Comment by schriftgestalt** [comment]
What do you mean? Use the period in the lookup name of only allow dot-suffixes?

**Pull request merged**
