### PR TITLE
Revert "Don't skip over spacing marks when kerning (#720)"

### PR DESCRIPTION
**Pull request by anthrotype**
This reverts PR #720 while we find a fix for https://github.com/googlefonts/ufo2ft/issues/721

### CODE REVIEW

**Comment by simoncozens** [comment]
I don't agree with reverting this. #720 is helpful in the small (but real) corner case of kerning between spacing combining marks. I don't think we should revert that benefit just because it crashes in the vanishingly tiny case of spacing marks with zero width in some masters.

**Comment by anthrotype** [comment]
ok.. but what would you do (or recommend users to do) as a workaround in that specific case?

**Comment by simoncozens** [comment]
If they want all masters to be treated as non-spacing, set the zero-width master to have width==1 unit.

**Comment by anthrotype** [comment]
let's hope this doesn't bite us later on

**Comment by madig** [comment]
Is this documented or warned about anywhere?

**Pull request closed without merging**
