### PR TITLE
iterClassDefinitions() should find nested class definitions

### PR DESCRIPTION
**Pull request by moyogo**
https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#2.g.ii
> Glyph class assignments can appear anywhere in the feature file. A glyph class name may be used in the feature file only after its definition.

Glyph class definitions can be top-level, inside a feature blocks but also inside a lookup block or inside lookup block itself inside a feature block. I guess other blocks like cvparameters or table would not make sense.

### CODE REVIEW

**Comment by anthrotype** [comment]
hey Denis! can you fix formatting with black, and also rebase on main where I made codecov not fail the PR checks (upload is flaky with PRs sometimes)

**Review by anthrotype — APPROVED** [review]
LGTM!

**Comment by moyogo** [comment]
Thank you!

**Comment by anthrotype** [comment]
feel free to merge when you get a LGTM from other co-maintainers, I think you already should have write access to this repo

**Pull request merged**
