### PR TITLE
don't drop implied oncurves for interpolatable TTFs when building a VF

### PR DESCRIPTION
**Pull request by anthrotype**
this should only be done at the end in the final VF, otherwise masters may end up with incompatible glyphs...

### CODE REVIEW

**Comment by anthrotype** [comment]
Added a test with a reproducer, which fails as expected.

https://github.com/googlefonts/ufo2ft/actions/runs/7804773235/job/21287495551?pr=817#step:5:217
```
WARNING  fontTools.varLib:__init__.py:1069 Failed to drop implied oncurves for 'o': Incompatible flags for glyph at master index 1: expected array('B', [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]), found array('B', [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
INFO     fontTools.varLib:__init__.py:1170 Dropped 0 on-curve points from simple glyphs in the 'glyf' table
``

**Comment by behdad** [comment]
Does varLib do it?

**Comment by anthrotype** [comment]
this issue might have been noticed earlier if varLib errored instead of just warning: https://github.com/fonttools/fonttools/issues/2572

**Comment by anthrotype** [comment]
> Does varLib do it?

yes, we do it either in the TTGlyphPen (for the static fonts) or in varLib (for the variable ones)

**Comment by anthrotype** [comment]
this is a regression from #801 when we moved things around. The previous code was pop'ing the the dropImpliedOnCurves parameter from the kwargs before making the outline compiler for the VF's interpolatable masters and then passing it on to varLib.build

**Pull request merged**
