### PR TITLE
define 'colrClipBoxes' lib key, pass it on to buildCOLR

### PR DESCRIPTION
**Pull request by anthrotype**
To be able to build a COLRv1 ClipList using the new api defined in https://github.com/fonttools/fonttools/pull/2379

### CODE REVIEW

**Comment by behdad** [comment]
I suggest `colr` instead of `color`. There's nothing colorful about this property. Its description is that it's used by `colr` table; which, we allow for non-color use as well.

**Comment by anthrotype** [comment]
for the new lib key, I used the name "colorClipBoxes" because there are already 3 other similar lib keys that also start with `"color*"`: i.e. "colorLayers", "colorPalettes" and "colorLayerMapping". I see what you mean but I believe it may be a bit confusing to now add `colrClipBoxes` right next to the other ones.
Maybe I can add aliases for the other ones with a `colr` prefix and accept both (and deprecate the old ones..)

**Comment by behdad** [comment]
> for the new lib key, I used the name "colorClipBoxes" because there are already 3 other similar lib keys that also start with `"color*"`: i.e. "colorLayers", "colorPalettes" and "colorLayerMapping". I see what you mean but I believe it may be a bit confusing to now add `colrClipBoxes` right next to the other ones.

Fair enough.

**Comment by anthrotype** [comment]
> Fair enough.

I actually changed my mind and now agree with you (https://github.com/googlefonts/ufo2ft/pull/521/commits/e54ef4c085dbe3c59c5e72229bcb8ee8008b4ab6) LOL

**Pull request merged**
