### PR TITLE
Automatically decompose when 2x2 transforms differ

### LINKED ISSUE #507: decomposeTransformedComponents does not account for variable fonts
I have been getting errors on my build project where it is being reported that some glyphs in the font have a different number of segments. In reviewing the glyphs, I realized that what is happening is that in the lighter weights, there are components that have been transformed, but in the heaviest weight, they are not transformed. So the decomposeTransformedComponents filter is decomposing them in the lighter weights, but not the heaviest weight. 

In a situation where compileVariableTTF is being run, it would make sense for decomposeTransformedComponents to check the components across all UFOs and decompose all of them if one is transformed in order to maintain compatibility.

### PR DESCRIPTION
**Pull request by simoncozens**
This fixes #507 (again).

- Decompose glyphs if they have non-matching transforms
- Compare the relevant part of the transformation only
- Add a test

### CODE REVIEW

**Review by anthrotype — APPROVED** [review]
this is good, thanks Simon!

**Comment by anthrotype** [comment]
can you also check if https://github.com/googlefonts/ufo2ft/issues/695 gets fixed by this too?

**Comment by simoncozens** [comment]
I'm not sure. It looks OK to me, but it also looks OK with the main branch as well. However, it *was* previously giving

```
WARNING:fontTools.varLib:glyph Ohorntilde has incompatible masters; skipping
```

and now it doesn't, so maybe?

**Comment by anthrotype** [comment]
yeah, that's it! varLib is dropping the variations for that composite glyph because the master components' transform do not match (I think as result of this recent change in fonttools => https://github.com/fonttools/fonttools/pull/2857)

**Comment by anthrotype** [comment]
if you drop the font built with this branch in fontgoggles and type "ỡỠ" do both vary as you move along the wght axis? /cc @yanone 

in that case, I would mark #695 as fixed by this as well

**Comment by simoncozens** [comment]
Yes, they do. But as I said, they seemed to do that for me before. I think it might involve different versions of fonttools too.

**Pull request merged**
