### PR TITLE
Use fontTools.cu2qu instead of cu2qu

### PR DESCRIPTION
**Pull request by simoncozens**
According to https://github.com/googlefonts/cu2qu/issues/191, cu2qu (the independent Python module) has ceased development and has now been folded into fontTools. This PR changes ufo2ft to use the fontTools version.

### CODE REVIEW

**Comment by anthrotype** [comment]
We didn't replace it yet intentionally, because the standalone cu2qu is accelerated using cython the fonttools one is pure python thus slower. The two modules are still in sync, no new features was added in the fonttools copy that warrants losing the speed-up.
Why do you want to to this now?

**Comment by anthrotype** [comment]
If you like we could make it optional, have ufo2ft first try to import the standalone cu2qu and then fall back to fonttools cu2qu. But I want to understand the reason first

**Comment by simoncozens** [comment]
The issue I linked suggests that the standalone module is dead and replaced by fontTools, so I thought it would make sense to use the not-dead implementation. I didn’t know about the Cython optimisation. I agree it would be a shame to lose that. I wonder why it wasn’t brought over.

**Comment by anthrotype** [comment]
> I wonder why it wasn’t brought over.

Actually it was! But it's only enabled if you build fonttools from source and you have cython already installed, or if you explicitly pass an optional build-time flag to fonttools setup.py (`--with-cython` or exporting `FONTTOOLS_WITH_CYTHON=1` environment variable). We didn't enable this by default for the standard fonttools wheel package that we distribute over PyPI because we wanted to keep the traditional pure-python-ness of fonttools.

**Comment by bkmgit** [comment]
It would likely be good for the environment to enable Cython optimization in fonttools to minimize software energy consumption.

**Comment by anthrotype** [comment]
this has already happened so can be closed

**Pull request closed without merging**
