### PR TITLE
Find earliest opportunity to insert lookups/mark classes/anchors

### PR DESCRIPTION
**Pull request by simoncozens**
Potential fix for #504

### CODE REVIEW

**Review by anthrotype — COMMENTED** [review]
it would be nice to have an accompanying test

**Comment by moyogo** [comment]
Thanks @simoncozens !

**Comment by moyogo** [comment]
I added a test in 86c3357aa535d3eec73f8440435838c112eae639

**Comment by simoncozens** [comment]
Thank you!

**Pull request merged**
