### PR TITLE
[tests] Update expectations for fonttools TTX Format change

### PR DESCRIPTION
**Pull request by behdad**
That is https://github.com/fonttools/fonttools/pull/2238

Perhaps needs a fonttools release and bumping dep. But sharing here since I did this part already.

### CODE REVIEW

**Comment by behdad** [comment]
Also maybe give me some privileges on this repo? I can't assign reviewers etc.

**Comment by madig** [comment]
I think I also updated the test data in https://github.com/googlefonts/ufo2ft/pull/486 😬 and I don't have admin rights.

**Comment by moyogo** [comment]
> Also maybe give me some privileges on this repo? I can't assign reviewers etc.

Does it work now?

**Comment by behdad** [comment]
All good. Thanks. Feel free to close in favor of madig's. Or update deps and land this and land his on top.

**Pull request closed without merging**
